# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Buy It Sell It' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Buy It Sell It
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'LinearProgressBar'
  pod 'IQKeyboardManagerSwift', '5.0.0'
  pod 'SDWebImage/WebP'
  pod 'FTImageSize', '~> 0.0.4'

  target 'Buy It Sell ItTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Buy It Sell ItUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
